version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:22.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - firebase.json

  deploy:
    docker:
      - image: cimg/node:22.0.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Firebase
          command: npx firebase-tools deploy --only hosting:salesForcast --token $FIREBASE_TOKEN

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
